export * from './auth/auth.module';
export * from './demo/demo.module';
export * from './users/users.module';
export * from './classes/classes.module';
export * from './students/students.module';
export * from './guardians/guardians.module';
export * from './enrollments/enrollments.module';
export * from './academic-years/academic-years.module';
export * from './class-templates/class-templates.module';
